//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public System.DateTime OpenDate { get; set; }
        public int UserId { get; set; }
        public decimal Balance { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> MonthlyFee { get; set; }
        public System.DateTime InterestFeeDate { get; set; }
        public int AccountTypeId { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public bool IsActive { get; set; }
        // Status(active/notActive)
        public string Status { get { return IsActive? "Active" : "Inactive"; } }

    public virtual AccountType AccountType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
