//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedCode
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Transaction
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> ToAccount { get; set; }
        public string Type { get; set; }
        public string PaymentCategory { get; set; }
        public int AccountId { get; set; }

        //account balance after this transaction
        public decimal AccBalanceAfterTrans { get { return CalculateBalanceAfterParticularTransaction(); } }

        public virtual Account Account { get; set; }

        //calculate account balance after particular transaction
        public decimal CalculateBalanceAfterParticularTransaction()
        {
            List<Transaction> transactions = null;
            decimal balance = 0;
            try
            {
                 transactions = EFData.context.Transactions.Where(t => t.AccountId == AccountId && t.Id <= Id).ToList();
            }
            catch(SystemException ex)
            {
                Console.WriteLine("Database error: " + ex.Message);
            }

            foreach (Transaction t in transactions)
            {
                if (t.Type == "Deposit")
                {
                    balance = balance + t.Amount;
                }
                else
                {
                    balance = balance - t.Amount;
                }
            }
            return balance;
        }
    }
}
